#!/bin/sh
### BEGIN INIT INFO
# Provides:          ErabliCollecteur
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop era
### END INIT INFO

# More details see: 

### Customize this entry
# Set the USER variable to the name of the user to start ErabliCollecteur under
export USER='pi'
### End customization required

eval cd ~$USER

case "$1" in
  start)
# Create a detached screen session called ErabliCollecteur
	su $USER -c 'screen -d -m -S ErabliCollecteur'
	su $USER -c 'screen -X -S ErabliCollecteur cd /home/pi/node_projects/ErabliCollecteur'
# Execute the node app.js in that screen
    su $USER -c 'screen -X -S ErabliCollecteur node app.js  '
    echo "Starting ErabliCollecteur server for $USER on screen ErabliCollecteur"
    ;;
  stop)
    pkill ErabliCollecteur
    echo "ErabliCollecteur stopped"
    ;;
  *)
    echo "Usage: /etc/init.d/ErabliCollecteur {start|stop}"
    exit 1
    ;;
esac
exit 0

